[package]
name = "lft-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.4"
log = "0.4.17"
num_cpus = "1.13"
pretty_env_logger = "0.4.0"
queues="1.1.0"
lockfree="0.5.1"
npy="0.4.0"
